CoreMVCTestMVC/Areas/Admin/Controllers/BackgroundManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreMVCTestDB;
using CoreMVCTestDB.Models.PublicModel;
using CoreMVCTestMVC.Areas.Admin.Models;
using PassWord_Help;
using Microsoft.Extensions.Options;
using CoreMVCTestMVC.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace CoreMVCTestMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BackgroundManagementController : Controller
    {
        private readonly CoreMVCTestContext _context;
      
        public BackgroundManagementController(CoreMVCTestContext context)
        {
            _context = context;
           
        }

  
        // GET: Admin/BackgroundManagement
        public async Task<IActionResult> Index()
        {
            return View();
        }
        //public IActionResult OnGet()
        //{
        //    //登录授权直接跳转index界面
        //    if (HttpContext.User.Identity.IsAuthenticated)
        //    {
        //        return RedirectToPage("Index", "BackgroundManagement");
        //    }
        //    return RedirectToAction("Login", "BackgroundManagement");
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Test([Bind(include:"UserName,AdminPassWord")] AdminLogin login)
        {
            if (ModelState.IsValid)
            {
                var password = PassWordHelp.MD5Encrypt32(login.AdminPassWord);
                var y = _context.Users.Where(x => x.UserName == login.UserName && x.PasswordHash == password).FirstOrDefault();
                if (y != null)
                {
                    
                }
                #region 登录授权
                //登录授权
                var claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, login.UserName));
                var indentity = new ClaimsIdentity(claims, "denglu");
                var principal = new ClaimsPrincipal(indentity);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                if (principal.Identity.IsAuthenticated)
                {

                }
                #endregion
                return RedirectToAction(nameof(Index));
            }
            return View(login);
        }
        #region 默认生成
        // GET: Admin/BackgroundManagement/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userLogins = await _context.UserLogins
                .FirstOrDefaultAsync(m => m.ProviderKey == id);
            if (userLogins == null)
            {
                return NotFound();
            }

            return View(userLogins);
        }

        // GET: Admin/BackgroundManagement/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/BackgroundManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LoginProvider,ProviderKey,ProviderDisplayName,UserId")] UserLogins userLogins)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userLogins);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userLogins);
        }

        // GET: Admin/BackgroundManagement/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userLogins = await _context.UserLogins.FindAsync(id);
            if (userLogins == null)
            {
                return NotFound();
            }
            return View(userLogins);
        }

        // POST: Admin/BackgroundManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("LoginProvider,ProviderKey,ProviderDisplayName,UserId")] UserLogins userLogins)
        {
            if (id != userLogins.ProviderKey)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userLogins);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserLoginsExists(userLogins.ProviderKey))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userLogins);
        }

        // GET: Admin/BackgroundManagement/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userLogins = await _context.UserLogins
                .FirstOrDefaultAsync(m => m.ProviderKey == id);
            if (userLogins == null)
            {
                return NotFound();
            }

            return View(userLogins);
        }

        // POST: Admin/BackgroundManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var userLogins = await _context.UserLogins.FindAsync(id);
            _context.UserLogins.Remove(userLogins);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion
        private bool UserLoginsExists(string id)
        {
            return _context.UserLogins.Any(e => e.ProviderKey == id);
        }
    }
}

CoreMVCTestMVC/Areas/Admin/Views/BackgroundManagement/Create.cshtml
@model CoreMVCTestDB.Models.PublicModel.UserLogins

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>
<h4>UserLogins</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LoginProvider" class="control-label"></label>
                <input asp-for="LoginProvider" class="form-control" />
                <span asp-validation-for="LoginProvider" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProviderKey" class="control-label"></label>
                <input asp-for="ProviderKey" class="form-control" />
                <span asp-validation-for="ProviderKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProviderDisplayName" class="control-label"></label>
                <input asp-for="ProviderDisplayName" class="form-control" />
                <span asp-validation-for="ProviderDisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMVCTestMVC/Areas/Admin/Views/BackgroundManagement/Delete.cshtml
@model CoreMVCTestDB.Models.PublicModel.UserLogins

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserLogins</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProviderDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProviderDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LoginProvider" />
        <input type="hidden" asp-for="ProviderKey" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CoreMVCTestMVC/Areas/Admin/Views/BackgroundManagement/Details.cshtml
@model CoreMVCTestDB.Models.PublicModel.UserLogins

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>UserLogins</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProviderDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProviderDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CoreMVCTestMVC/Areas/Admin/Views/BackgroundManagement/Edit.cshtml
@model CoreMVCTestDB.Models.PublicModel.UserLogins

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>UserLogins</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LoginProvider" />
            <input type="hidden" asp-for="ProviderKey" />
            <div class="form-group">
                <label asp-for="ProviderDisplayName" class="control-label"></label>
                <input asp-for="ProviderDisplayName" class="form-control" />
                <span asp-validation-for="ProviderDisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoreMVCTestMVC/Areas/Admin/Views/BackgroundManagement/Index.cshtml
@model CoreMVCTestMVC.Areas.Admin.Models.AdminLogin

@{
    ViewData["Title"] = "后台登陆";
    Layout = "~/Views/Shared/_LayoutOriginal.cshtml";
}
<div class="container text-center">
    <h1 class="h3 mb-3 font-weight-normal">请登录</h1>
    @using (Html.BeginForm("Test", "BackgroundManagement", new { Area = "Admin" }, FormMethod.Post, true, new { @class = "form-signin" }))
    {
        @Html.LabelFor(model => model.UserName, new { @class = "sr-only" })

        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { type = "text", @class = "form-control", placeholder = "用户名", @autocomplete = "off" } })
        @Html.ValidationMessageFor(model => model.UserName, null, new { @class = "text-danger text-right float-left" })

        @Html.LabelFor(model => model.AdminPassWord, new { @class = "sr-only" })

        @Html.PasswordFor(model => model.AdminPassWord, new { @class = "form-control", @autocomplete = "off", title = "密码不能少于6位" })
        @Html.ValidationMessageFor(model => model.AdminPassWord, null, new { @class = "text-danger text-right float-left" })

        <button class="btn btn-lg btn-primary btn-block " type="submit">登录</button>

        @Html.ValidationSummary(true)
    }

    @section Scripts {
        <script type="text/javascript">

            $(document).ready(function () {
                //$("input").removeClass();
                //$("#AdminPassWord").addClass("form-control");
                ////$("#AdminPassWord").attr("placeholder", "密码");
                $("#AdminPassWord").attr({ "placeholder": "密码", "data-toggle": "tooltip", "title": "密码不能少于6位", "data-placement": "right" });
                //$("#UserName").addClass("form-control");
                //$("#UserName").addClass("")
                $(function () {
                    $('[data-toggle="tooltip"]').tooltip();
                });
                $("#UserName").focus();
            });
            function isUsername(str) {
                var regUsername = /^[A-Za-z0-9\u4e00-\u9fa5]+$/; /*定义验证表达式*/
                return regUsername.test(str); /*定义验证表达式*/
            };
            /*校验密码*/
            function isPassword(str) {
                var regPassword = /^[\w]{6,18}$/;
                return regPassword.test(str);
            };
            $('#UserName,#AdminPassWord').focusout(function () {
                var username = $('#UserName').val();
                var password = $('#AdminPassWord').val();
                var state = false;
                if (username != "" && password != "") {
                    if (!isUsername(username)) {
                        $('#UserName').addClass("border-warning");
                        state = false;
                    }
                    if (!isPassword(password)) {
                        $('#AdminPassWord').addClass("border-warning");
                        state = false;
                    }

                    if (isUsername(username) && isPassword(password)) {
                        state = true;
                        $('#UserName').removeClass("border-warning");
                        $('#AdminPassWord').removeClass("border-warning");
                    }
                }
                else {
                    if (username == "") {
                        $('#UserName').addClass("border-warning");
                    }
                    if (password = "") {
                        $('#AdminPassWord').addClass("border-warning");
                        state = false;
                    }
                };

            });
        </script>
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>